<?php $themes_index = array (
   'gem',
   'awada',
   'kyma',
   'venture-lite',
   'ornea',
   'blogrock-core',
   'beam',
   'shamrock',
   'i-craft',
   'thewest',
   'matrix',
   'juniper',
   'topcat-lite',
   'infiword',
   'agama',
   'safreen',
);