<?php $plugins_index = array (
   'border-loading-bar',
   'catchers-helpdesk',
   'cf7-customizer',
   'simple-behace-portfolio',
   'adblock-notify-by-bweb',
   'affiliate-pro',
   'tr-easy-google-analytics',
   'epic-selection-sharer',
   'betteroptin',
   'titan-framework',
   'mobile-menu',
   'aoi-tori',
   'awesome-support',
);